// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/:lang/documentation/*": {
    params: {
      "lang": string;
      "*": string;
    };
  };
  "/llms.txt": {
    params: {};
  };
  "/no-language/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*" | "/:lang/documentation/*" | "/llms.txt" | "/no-language/*";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/*" | "/:lang/documentation/*" | "/llms.txt" | "/no-language/*";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "routes/$lang/documentation/$.tsx": {
    id: "routes/$lang/documentation/$";
    page: "/:lang/documentation/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/llms.txt.tsx": {
    id: "routes/llms.txt";
    page: "/llms.txt";
  };
  "routes/no-language/$.tsx": {
    id: "routes/no-language/$";
    page: "/no-language/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/_layout": typeof import("./src/app/routes/_layout.tsx");
  "routes/$": typeof import("./src/app/routes/$.tsx");
  "routes/$lang/documentation/$": typeof import("./src/app/routes/$lang/documentation/$.tsx");
  "routes/_index": typeof import("./src/app/routes/_index.tsx");
  "routes/llms.txt": typeof import("./src/app/routes/llms.txt.tsx");
  "routes/no-language/$": typeof import("./src/app/routes/no-language/$.tsx");
};