// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/documentation/*": {
    params: {
      "*": string;
    };
  };
  "/llms.txt": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*" | "/documentation/*" | "/llms.txt";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/*" | "/documentation/*" | "/llms.txt";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/documentation/$.tsx": {
    id: "routes/documentation/$";
    page: "/documentation/*";
  };
  "routes/llms.txt.tsx": {
    id: "routes/llms.txt";
    page: "/llms.txt";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/_layout": typeof import("./src/app/routes/_layout.tsx");
  "routes/$": typeof import("./src/app/routes/$.tsx");
  "routes/_index": typeof import("./src/app/routes/_index.tsx");
  "routes/documentation/$": typeof import("./src/app/routes/documentation/$.tsx");
  "routes/llms.txt": typeof import("./src/app/routes/llms.txt.tsx");
};